[project]
name = "voice-search-using-python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pyaudio>=0.2.14",
    "speechrecognition>=3.14.3",
]
